[package]
name = "sieve-of-eratosthenes-rust"
version = "0.1.0"
authors = ["Connor Hawley <connor.hawley4@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"